from pydantic import BaseModel, Field
from datetime import datetime, date, time
from typing import Optional, List, Dict, Any
import uuid


class SleepStages(BaseModel):
    awakeMinutes: Optional[int] = Field(0, description="Awake duration in minutes")
    lightMinutes: Optional[int] = Field(0, description="Light sleep duration in minutes")
    deepMinutes: Optional[int] = Field(0, description="Deep sleep duration in minutes")
    remMinutes: Optional[int] = Field(0, description="REM sleep duration in minutes")


class SleepSessionCreate(BaseModel):
    id: str = Field(..., description="UUID of the sleep session generated by frontend")
    startTime: datetime = Field(..., description="Time when sleep started (timezone aware)")
    endTime: datetime = Field(..., description="Time when sleep ended (timezone aware)")
    isNap: bool = Field(False, description="Whether this sleep is a nap")
    timezone: str = Field("UTC", description="IANA timezone name, e.g. Asia/Kolkata")
    source: str = Field("manual", description="Source of tracking, e.g., manual, device")
    
    # Nested stages object sent by modern frontend
    stages: Optional[SleepStages] = Field(None, description="Detailed sleep stages structure")
    
    # Flat fields retained for backward compatibility
    deepSleepMinutes: Optional[int] = Field(0, description="Deep sleep duration in minutes")
    lightSleepMinutes: Optional[int] = Field(0, description="Light sleep duration in minutes")
    remSleepMinutes: Optional[int] = Field(0, description="REM sleep duration in minutes")
    awakeMinutes: Optional[int] = Field(0, description="Awake duration during sleep in minutes")
    
    # Frontend metadata fields (ignored in service calculations but allowed in schemas)
    durationMinutes: Optional[int] = Field(None, description="Duration in minutes (calculated by backend)")
    qualityScore: Optional[int] = Field(None, description="Sleep quality score (calculated by backend)")
    synced: Optional[bool] = Field(None, description="Offline sync status")
    updatedAt: Optional[datetime] = Field(None, description="Last update timestamp from frontend")


class SleepSessionUpdate(BaseModel):
    startTime: Optional[datetime] = None
    endTime: Optional[datetime] = None
    isNap: Optional[bool] = None
    timezone: Optional[str] = None
    source: Optional[str] = None
    
    # Nested stages update
    stages: Optional[SleepStages] = None
    
    # Flat fields update
    deepSleepMinutes: Optional[int] = None
    lightSleepMinutes: Optional[int] = None
    remSleepMinutes: Optional[int] = None
    awakeMinutes: Optional[int] = None
    
    # Frontend metadata fields
    durationMinutes: Optional[int] = None
    qualityScore: Optional[int] = None
    synced: Optional[bool] = None
    updatedAt: Optional[datetime] = None


class SleepSessionResponse(BaseModel):
    id: uuid.UUID
    user_id: int
    start_time: datetime
    end_time: datetime
    duration_minutes: int
    sleep_score: int
    sleep_quality: str
    is_nap: bool
    session_source: str
    timezone: str
    deep_sleep_minutes: int
    light_sleep_minutes: int
    rem_sleep_minutes: int
    awake_minutes: int
    synced_at: Optional[datetime] = None
    created_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True


class UserDailySleepResponse(BaseModel):
    id: int
    user_id: int
    sleep_date: date
    total_sleep_minutes: int
    total_sessions: int
    avg_sleep_score: float
    total_deep_sleep: int
    total_rem_sleep: int
    total_light_sleep: int
    sleep_consistency_score: int
    bed_time_avg: Optional[time] = None
    wake_time_avg: Optional[time] = None
    created_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True


class UserMonthlySleepResponse(BaseModel):
    id: int
    user_id: int
    year: int
    month: int
    total_sleep_minutes: int
    avg_sleep_minutes: float
    avg_sleep_score: float
    total_sessions: int
    best_sleep_score: int
    worst_sleep_score: int
    avg_deep_sleep: float
    avg_rem_sleep: float
    sleep_consistency_score: float
    days_tracked: int
    created_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True


class UserYearlySleepResponse(BaseModel):
    id: int
    user_id: int
    year: int
    total_sleep_minutes: int
    avg_sleep_minutes: float
    avg_sleep_score: float
    total_sessions: int
    days_tracked: int
    best_month_score: float
    worst_month_score: float
    sleep_consistency_score: float
    created_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True


class SleepHistoryResponse(BaseModel):
    sessions: List[SleepSessionResponse]
    total: int
    page: int
    limit: int


class WeeklySleepData(BaseModel):
    sleep_date: date
    total_sleep_minutes: int
    sessions_count: int
    sleep_score: float
    deep_sleep_minutes: int
    rem_sleep_minutes: int
    light_sleep_minutes: int


class SleepAnalyticsResponse(BaseModel):
    average_sleep_minutes: float
    average_sleep_score: float
    total_sessions: int
    days_tracked: int
    sleep_streak_current: int
    sleep_streak_longest: int
    weekly_history: List[WeeklySleepData]
